apiVersion: v1
kind: Pod
metadata:
  name: repo_name
  labels:
    heritage: deis
    version: 2.0.0-alpha2
spec:
  restartPolicy: Never
  containers:
    - name: deis-slugbuilder
      imagePullPolicy: Always
      image: quay.io/deisci/slugbuilder:v2-alpha2
      env:
        - name: TAR_URL
          value: tar-url
        - name : put_url
          value: puturl
      volumeMounts:
        - name: minio-user
          mountPath: /var/run/secrets/object/store
          readOnly: true
  volumes:
    - name: minio-user
      secret:
        secretName: minio-user
